name: My First Workflow Self Hosted
on: workflow_dispatch
jobs:
  my-first-job:
    runs-on: self-hosted
    steps:
      - name: Print Hello
        run: |
          echo "Hello World"
          echo "Show me from behind the wall"
      - name: Print project main folder path
        run: pwd
      - name: Print processor speed
        run: lscpu
