name: Workflow Job1 depends-on Job2
on: workflow_dispatch

jobs:
  
  job1:
    runs-on: ubuntu-latest
    outputs:
      my_output: ${{ steps.job1.outputs.my_output }}
    steps:
      - name: Job 1
        id: job1
        # run: echo "Set some value"
        run: |
          if [ 1 -gt 0 ]
          then
            echo "my_output=true" >> "$GITHUB_OUTPUT"
            echo "That is correct"
          else
            echo "my_output=false" >> "$GITHUB_OUTPUT"
            echo "That is wrong"
          fi
          echo ""      
      - name: 'print job1 outputs'
        run: echo ${{ steps.job1.outputs.my_output }}
  
  job2:
    runs-on: ubuntu-latest  
    needs: job1  
    steps:
      - name: 'print job1 outputs'
        run: echo ${{ needs.job1.outputs.my_output }}

      - name: Job 2
        id: job2
        run: |
          echo "That is correct"
          if ${{ needs.job1.outputs.my_output }}; then
          echo "The condition was met!"   
          else
            echo "The condition was not met!" 
          fi
