name: My First Workflow Self Hosted
on: workflow_dispatch
jobs:
  my-first-job:
    runs-on: self-hosted
    steps:
      - name: Print Hello
        run: echo "Hello World"
      - name: Print project main folder path
        run: echo pwd
